### ISSUE TITLE
STL Implementation

### ISSUE THREAD

**Issue by OragonEfreet** [OragonEfreet/cog#18]
Create a REAL STL implementation independent from the rest of the project with:

- Currently in subdir but possibly later its own git repos
- namespace cogstl  or oestl

CMake:
For further CMAKE configuration explicitly use the namespace for the moment.

**Comment by OragonEfreet** [comment]
JE REPONDS SI JE VEUX !

**Comment by OragonEfreet** [comment]
En fait si tu regardes au dessus de ce texte tu verras que c'est pas un _commit_ mais un _comment_.

**Comment by Menestrels** [comment]
C'est bien !

**Comment by OragonEfreet** [comment]
Use STL for now. CogSTL will be a separate project.
